version: '3.8'
services:
  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.wal-compression'
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
          cpus: '0.5'
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.7.3
    container_name: loki
    volumes:
      - ./loki-config.yaml:/etc/loki/loki.yaml
      - loki-data:/loki/data
    environment:
      - LOKI_STORAGE_PATH=/loki/data
    ports:
      - "3100:3100"
    command:
      - '-config.file=/etc/loki/loki.yaml'
      - '-config.expand-env=true'
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
          cpus: '0.3'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SERVER_HTTP_PORT=3000
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_INSTALL_PLUGINS=
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
          cpus: '0.2'
    networks:
      - monitoring

  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    command:
      - '--path.rootfs=/host'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
          cpus: '0.1'
    networks:
      - monitoring

volumes:
  grafana-storage:
  prometheus-data:
  loki-data:

networks:
  monitoring:
    driver: bridge
