
version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - /var/www/vendor
      - /var/www/node_modules
    depends_on:
      - database
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
          cpus: '0.25'
    environment:
      # PHPのメモリ制限を最適化
      PHP_MEMORY_LIMIT: 128M
      COMPOSER_MEMORY_LIMIT: -1
      # OPcacheの設定を追加
      PHP_OPCACHE_ENABLE: 1
      PHP_OPCACHE_MEMORY_CONSUMPTION: 64M
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 0
      # JITコンパイラの有効化 (PHP 8.0+)
      PHP_OPCACHE_JIT: 1255
      PHP_OPCACHE_JIT_BUFFER_SIZE: 100M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www:ro
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - app
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
          cpus: '0.1'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  database:
    image: mysql:8.0-oracle
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: pechipechi
      # MySQLの最適化設定
      MYSQL_INNODB_BUFFER_POOL_SIZE: 128M
      MYSQL_INNODB_LOG_FILE_SIZE: 32M
      MYSQL_MAX_CONNECTIONS: 20
      MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT: 2
      MYSQL_INNODB_FLUSH_METHOD: O_DIRECT
    volumes:
      - dbdata:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 256M
          cpus: '0.5'
    command: >
      --performance-schema=0
      --table_definition_cache=200
      --table_open_cache=400
      --skip-name-resolve
      --innodb_buffer_pool_size=128M
      --innodb_log_file_size=32M
      --max_connections=20
      --innodb_flush_log_at_trx_commit=2
      --innodb_flush_method=O_DIRECT
      --default-authentication-plugin=mysql_native_password
      --transaction-isolation=READ-COMMITTED
      --binlog-expire-logs-seconds=86400
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

volumes:
  dbdata:
    driver: local
